ROOT=$(python -c "from config import ROOT; print(ROOT)")

# MongoDB
$ROOT/mongodb-7.0.20/bin/mongod \
    --port=27017 \
    --dbpath=$ROOT/data/mongodb/data \
    --logpath=$ROOT/data/mongodb/logs/mongodb.log \
    --bind_ip=0.0.0.0 \
    --fork

# vLLM
nohup python -m vllm.entrypoints.openai.api_server \
    --model $ROOT/data/llm/quantized \
    --port 8000 \
    --dtype float16 \
    --quantization awq \
    --max-model-len 4096 \
    --gpu-memory-utilization 0.75 \
    > $ROOT/logs/vllm.log 2>&1 &
sleep 60